// Build-time theme CSS generator (#32). Reads the hand-authored theme JSON
// files in apps/web/themes/ and writes one static CSS file with a
// [data-theme="name"] block per theme, plus a :root fallback (equal to the
// default theme) so pre-hydration/no-JS renders aren't unstyled. Themes stay
// pure data; this script is the only thing that turns them into CSS.
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath, pathToFileURL } from "url";

const ROLES = [
  "background",
  "surface",
  "text",
  "textMuted",
  "accent",
  "border",
  "danger",
] as const;

// CSS custom properties are kebab-case; role names are camelCase in JSON.
const cssVarName = (role: string) =>
  `--${role.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`;

export type ThemeRoles = Record<(typeof ROLES)[number], string>;
export interface Theme {
  name: string;
  roles: ThemeRoles;
}

export function loadThemes(themesDir: string): Theme[] {
  const files = readdirSync(themesDir).filter((f) => f.endsWith(".json"));
  if (files.length === 0) {
    throw new Error(`No theme JSON files found in ${themesDir}`);
  }
  return files
    .map((file) => {
      const theme = JSON.parse(
        readFileSync(join(themesDir, file), "utf8"),
      ) as Theme;
      const missing = ROLES.filter((role) => !theme.roles?.[role]);
      if (missing.length > 0) {
        throw new Error(
          `Theme "${theme.name}" (${file}) is missing role(s): ${missing.join(", ")}`,
        );
      }
      return theme;
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

function themeBlock(selector: string, theme: Theme): string {
  const lines = ROLES.map(
    (role) => `  ${cssVarName(role)}: ${theme.roles[role]};`,
  );
  return `${selector} {\n${lines.join("\n")}\n}`;
}

// A tiny generated TS module listing theme names, so client components
// (e.g. the theme toggle) can know the catalog without doing fs reads —
// keeps "add a JSON file" the only step needed to extend the catalog.
export function generateManifest(
  themes: Theme[],
  defaultThemeName: string,
): string {
  const names = themes.map((t) => JSON.stringify(t.name)).join(", ");
  return [
    "// Generated by scripts/generate-theme-css.ts — do not edit by hand.",
    `export const THEME_NAMES = [${names}] as const;`,
    "export type ThemeName = (typeof THEME_NAMES)[number];",
    `export const DEFAULT_THEME: ThemeName = ${JSON.stringify(defaultThemeName)};`,
    "",
  ].join("\n");
}

export function generateCss(themes: Theme[], defaultThemeName: string): string {
  const defaultTheme = themes.find((t) => t.name === defaultThemeName);
  if (!defaultTheme) {
    throw new Error(
      `Default theme "${defaultThemeName}" not found among: ${themes.map((t) => t.name).join(", ")}`,
    );
  }
  const blocks = [
    "/* Generated by scripts/generate-theme-css.ts — do not edit by hand. */",
    themeBlock(":root", defaultTheme),
    ...themes.map((theme) => themeBlock(`[data-theme="${theme.name}"]`, theme)),
  ];
  return blocks.join("\n\n") + "\n";
}

// Only run the write side-effect when executed directly (not on import,
// e.g. from the test file). pathToFileURL normalizes the platform-specific
// argv[1] path (Windows drive letters, separators) to compare against
// import.meta.url reliably.
const isMain =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;

if (isMain) {
  const here = dirname(fileURLToPath(import.meta.url));
  const themesDir = join(here, "..", "themes");
  const cssFile = join(here, "..", "app", "theme-vars.css");
  const manifestFile = join(here, "..", "app", "theme-manifest.ts");
  const defaultThemeName = "black";

  const themes = loadThemes(themesDir);
  const css = generateCss(themes, defaultThemeName);
  const manifest = generateManifest(themes, defaultThemeName);

  mkdirSync(dirname(cssFile), { recursive: true });
  writeFileSync(cssFile, css, "utf8");
  writeFileSync(manifestFile, manifest, "utf8");
  console.log(
    `Generated ${cssFile} and ${manifestFile} (${themes.length} theme${themes.length === 1 ? "" : "s"}: ${themes.map((t) => t.name).join(", ")})`,
  );
}
