// Theme resolution (#32) — pure logic for turning the hand-authored theme
// catalog (apps/web/themes/*.json) into CSS var blocks and a name manifest.
// No fs, no Next/React imports (code-conventions.md's file-organization
// rule names "theme resolution" as lib/ material) — the only I/O
// (reading the JSON files, writing the generated output) lives in
// scripts/generate-theme-css.ts, which calls into here.

export const ROLES = [
  "background",
  "surface",
  "text",
  "textMuted",
  "accent",
  "border",
  "danger",
] as const;

export type ThemeRoles = Record<(typeof ROLES)[number], string>;
export interface Theme {
  name: string;
  roles: ThemeRoles;
}

// CSS custom properties are kebab-case; role names are camelCase in JSON.
export function cssVarName(role: string): string {
  return `--${role.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`)}`;
}

// Validates a theme parsed from JSON has every role — thrown message
// includes `source` (e.g. the file name) so a bad catalog entry points
// straight back at its file.
export function validateTheme(theme: Theme, source: string): void {
  const missing = ROLES.filter((role) => !theme.roles?.[role]);
  if (missing.length > 0) {
    throw new Error(
      `Theme "${theme.name}" (${source}) is missing role(s): ${missing.join(", ")}`,
    );
  }
}

function themeBlock(selector: string, theme: Theme): string {
  const lines = ROLES.map(
    (role) => `  ${cssVarName(role)}: ${theme.roles[role]};`,
  );
  return `${selector} {\n${lines.join("\n")}\n}`;
}

export function generateCss(themes: Theme[], defaultThemeName: string): string {
  const defaultTheme = themes.find((t) => t.name === defaultThemeName);
  if (!defaultTheme) {
    throw new Error(
      `Default theme "${defaultThemeName}" not found among: ${themes.map((t) => t.name).join(", ")}`,
    );
  }
  const blocks = [
    "/* Generated by scripts/generate-theme-css.ts — do not edit by hand. */",
    themeBlock(":root", defaultTheme),
    ...themes.map((theme) => themeBlock(`[data-theme="${theme.name}"]`, theme)),
  ];
  return blocks.join("\n\n") + "\n";
}

// A tiny generated TS module listing theme names, so client components
// (e.g. the theme toggle) can know the catalog without doing fs reads —
// keeps "add a JSON file" the only step needed to extend the catalog.
export function generateManifest(
  themes: Theme[],
  defaultThemeName: string,
): string {
  const names = themes.map((t) => JSON.stringify(t.name)).join(", ");
  return [
    "// Generated by scripts/generate-theme-css.ts — do not edit by hand.",
    `export const THEME_NAMES = [${names}] as const;`,
    "export type ThemeName = (typeof THEME_NAMES)[number];",
    `export const DEFAULT_THEME: ThemeName = ${JSON.stringify(defaultThemeName)};`,
    "",
  ].join("\n");
}
